services:
  # PHP-FPM
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: yii2_php
    volumes:
      - ./:/var/www
    environment:
      - PHP_MEMORY_LIMIT=512M
    networks:
      - yii2_network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: yii2_nginx
    ports:
      - "8080:80" # Сайт будет доступен на http://localhost:8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2_network

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: yii2_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yii2_network

  # Отдельный сервис для запуска Composer (чтобы не засорять основной PHP-контейнер)
  composer:
    image: composer:2
    container_name: yii2_composer
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - php
    networks:
      - yii2_network

volumes:
  db_data:

networks:
  yii2_network:
    driver: bridge